name: 'Archive All'
description: 'Build tarball with submodules included'
inputs:
  dir:
    description: Location of the checkout
    required: true
  name:
    description: Name of the release
    required: true
outputs:
  archive:
    description: name of archive generated
    value: ${{ steps.archive.outputs.archive }}
  sha256:
    description: checksum of archive generated
    value: ${{ steps.sha256.outputs.sha256 }}
runs:
  using: "composite"
  steps:
    - run: dir=${{ inputs.name }} && dir=${dir/-v/-} && echo "::set-output name=prefix::${dir}" && echo "::set-output name=archive::${dir}.tar.gz"
      id: archive
    - run: cd ${{ inputs.dir }} && ${{ github.action_path }}/git-archive-all.sh --prefix "${{ steps.archive.outputs.prefix }}"/ $GITHUB_WORKSPACE/"${{ steps.archive.outputs.archive }}"
      shell: bash
    - run: tar tf $GITHUB_WORKSPACE/${{ steps.archive.outputs.archive }}
      shell: bash
    - run: echo "::set-output name=sha256::$(sha256sum $GITHUB_WORKSPACE/${{ steps.archive.outputs.archive }})"
      id: sha256
      shell: bash
