name: 'Archive All'
description: 'Build tarball with submodules included'
inputs:
  dir:
    description: Location of the checkout
    required: true
  name:
    description: Name of the release
    required: true
outputs:
  archive:
    description: name of archive generated
    value: ${{ steps.archive.outputs.archive }}
  sha256:
    description: checksum of archive generated
    value: ${{ steps.sha256.outputs.sha256 }}
runs:
  using: "composite"
  steps:
    - run: |
      cd ${{ inputs.dir }} &&
      dir="${{ inputs.name }}" &&
      dir=${dir/-v/-} &&
      ${{ github.action_path }}/git-archive-all.sh --prefix "$dir"/ ../"$dir".tar.gz
      shell: bash
    - run: tar tf $GITHUB_WORKSPACE/${{ inputs.name }}.tar.gz
      shell: bash
    - run: echo "::set-output name=sha256::$(sha256sum $GITHUB_WORKSPACE/${{ inputs.name }}.tar.gz)"
      id: sha256
      shell: bash
    - run: echo "::set-output name=archive::${{ inputs.name }}.tar.gz"
      shell: bash
      id: archive
