name: 'Archive All'
description: 'Build tarball with submodules included'
inputs:
  dir:
    description: Location of the checkout
    required: true
  name:
    description: Name of the release
    required: true
outputs:
runs:
  using: "composite"
  steps:
    - run: cd ${{ inputs.dir }} && ${{ github.action_path }}/git-archive-all.sh --prefix ${{ inputs.name }}/ ../${{ inputs.name }}.tar.gz
      shell: bash
    - run: tar tf $GITHUB_WORKSPACE/${{ inputs.name }}.tar.gz
      shell: bash
    - run: echo "::set-output name=sha256::$(sha256sum $GITHUB_WORKSPACE/${{ inputs.name }}.tar.gz)"
      shell: bash
