name: x

on: push

jobs:
  archive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - user: gkdr
           repo: lurch
           ref: 'v0.7.0'
         - user: cisco
           repo: ChezScheme
           ref: 'v9.5.4'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ matrix.user }}/${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: repo
          submodules: true
      - uses: leahneukirchen/actions-archive-all@master
        id: archive_all
        with:
          dir: repo
          name: ${{ matrix.repo }}
          version: ${{ matrix.ref }}
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: ${{ matrix.repo }}-${{ matrix.ref }}
          body: |
            ${{ steps.archive_all.outputs.sha256 }}
          artifacts: ${{ steps.archive_all.outputs.archive }}

