name: x

on: push

jobs:
  archive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - user: gkdr
           repo: lurch
           ref: 'v0.7.0'
         - user: cisco
           repo: ChezScheme
           ref: 'v9.5.4'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ matrix.user }}/${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: repo
          submodules: true
      - uses: leahneukirchen/actions-archive-all@v0
        id: archive_all
        with:
          dir: repo
          name: ${{ matrix.repo }}-${{ matrix.ref }}
      # - run: echo ${{ join(steps.archive_all.outputs.*, ':') }}
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          tag_name: ${{ matrix.repo }}-${{ matrix.ref }}
          body: |
            ${{ steps.archive_all.outputs.sha256 }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.archive_all.outputs.archive }}
          asset_name: ${{ steps.archive_all.outputs.archive }}
          asset_content_type: application/gzip
